### ISSUE TITLE
IndexError: boolean index did not match indexed array along dimension 0; dimension is 84737 but corresponding boolean dimension is 84734

### ISSUE THREAD

**Issue by swh851168382** [KeiLongW/battery-state-estimation#10]
Hello, when reforking according to your program, why does the following error appear "IndexError: boolean index did not match indexed array along dimension 0; dimension is 84737 but corresponding boolean dimension is 84734"? Thank you so much

**Comment by KeiLongW** [comment]
Have you followed the instruction in the readme? Would you happen to have the required packages, the datasets, etc?
I need more information to understand the problem. For example, which line of codes did you encounter the error?

**Comment by swh851168382** [comment]
This error shows "2023/07/17 20:18:31 [INFO]: There is a NaN in cycle10degC/582_LA92, removing row
Traceback (most recent call last):
   File "G:\Graduate Thesis\OneDrive - stu.hebut.edu.cn\BMS PROJECT\soc_percentage.py", line 70, in <module>
     cycles = lg_data.get_discharge_whole_cycle(train_names, test_names, output_capacity=False, scale_test=True)
   File "G:\Graduate Thesis\OneDrive - stu.hebut.edu.cn\BMS PROJECT\DATA.py", line 18, in get_discharge_whole_cycle
     test = self._get_data(test_names, output_capacity, output_time) # get test data
   File "G:\Graduate Thesis\OneDrive - stu.hebut.edu.cn\BMS PROJECT\DATA.py", line 61, in _get_data
     y = y[~np.isnan(x).any(axis=1)].reshape(-1, y.shape[1])
IndexError: boolean index did not match indexed array along dimension 0; dimension is 84737 but corresponding boolean dimension is 84734
"I think it may be related to my attempt to convert the code into the pytorch framework. I just started deep learning and I am still groping

**Comment by KeiLongW** [comment]
As you are changing the code to your own version, I can't help much with your problem.
However, from your error, i see `y = y[~np.isnan(x).any(axis=1)].reshape(-1, y.shape[1])`. I guess the error is because of a typo in `np.isnan(x)`, should it be `np.isnan(y)`? as your are filtering the `y` array?

**Comment by swh851168382** [comment]
Sorry, I was careless, but after I corrected it still appeared "2023/07/17 20:35:07 [INFO]: There is a NaN in cycle10degC/582_LA92, removing row
Traceback (most recent call last):
   File "G:\Graduate Thesis\OneDrive - stu.hebut.edu.cn\BMS PROJECT\soc_percentage.py", line 70, in <module>
     cycles = lg_data.get_discharge_whole_cycle(train_names, test_names, output_capacity=False, scale_test=True)
   File "G:\Graduate Thesis\OneDrive - stu.hebut.edu.cn\BMS PROJECT\DATA.py", line 18, in get_discharge_whole_cycle
     test = self._get_data(test_names, output_capacity, output_time) # get test data
   File "G:\Graduate Thesis\OneDrive - stu.hebut.edu.cn\BMS PROJECT\DATA.py", line 26, in _get_data
     cycle.columns = ['Time Stamp', 'Step', 'Status', 'Prog Time', 'Step Time', 'Cycle', 'Cycle Level',
   File "H:\anaconda3\lib\site-packages\pandas\core\generic.py", line 5915, in __setattr__
     return object.__setattr__(self, name, value)
   File "pandas\_libs\properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
   File "H:\anaconda3\lib\site-packages\pandas\core\generic.py", line 823, in _set_axis
     self._mgr.set_axis(axis, labels)
   File "H:\anaconda3\lib\site-packages\pandas\core\internals\managers.py", line 230, in set_axis
     self._validate_set_axis(axis, new_labels)
   File "H:\anaconda3\lib\site-packages\pandas\core\internals\base.py", line 70, in _validate_set_axis
     raise ValueError(
ValueError: Length mismatch: Expected axis has 14 elements, new values have 15 elements" This error, I thought it was "cycle.columns = ['Time Stamp', 'Step', 'Status', 'Prog Time', 'Step' at first Time', 'Cycle', 'Cycle Level','Procedure', 'Voltage', 'Current','Temperature', 'Capacity', 'WhAccu', 'Cnt', 'Empty']" There are many I deleted the last Empty, but this problem still persists after deleting Empty, I am sorry to trouble you。

**Comment by KeiLongW** [comment]
I suggest to use other tools to open the csv to check the columns in the csv before assigning column names to it.
