### ISSUE TITLE
代码运行时出现以下错误？

### ISSUE THREAD

**Issue by GikM-max** [KeiLongW/battery-state-estimation#12]
D:\Anaconda\envs\DL\python.exe C:/Users/24451/Desktop/battery-state-estimation/battery-state-estimation/data_processing/lg_dataset.py
Traceback (most recent call last):
  File "C:\Users\24451\Desktop\battery-state-estimation\battery-state-estimation\data_processing\lg_dataset.py", line 253, in <module>
    cycles = lg_data.get_discharge_whole_cycle(train_names, test_names)
  File "C:\Users\24451\Desktop\battery-state-estimation\battery-state-estimation\data_processing\lg_dataset.py", line 16, in get_discharge_whole_cycle
    train = self._get_data(train_names, output_capacity, output_time)
  File "C:\Users\24451\Desktop\battery-state-estimation\battery-state-estimation\data_processing\lg_dataset.py", line 24, in _get_data
    cycle = pd.read_csv(self.path + name + '.csv', skiprows=30)
  File "D:\Anaconda\envs\DL\lib\site-packages\pandas\io\parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "D:\Anaconda\envs\DL\lib\site-packages\pandas\io\parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "D:\Anaconda\envs\DL\lib\site-packages\pandas\io\parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "D:\Anaconda\envs\DL\lib\site-packages\pandas\io\parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "D:\Anaconda\envs\DL\lib\site-packages\pandas\io\parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "D:\Anaconda\envs\DL\lib\site-packages\pandas\io\parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "D:\Anaconda\envs\DL\lib\site-packages\pandas\io\common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: './data/LG 18650HG2 Li-ion Battery Data/LG_HG2_Original_Dataset_McMasterUniversity_Jan_2020/25degC/551_LA92.csv'

第一步和第二部我的环境都没有问题，到第三步我应该怎么操作才可以运行起来？
求答复，谢谢

**Comment by KeiLongW** [comment]
make sure you downloaded the dataset and place it under the `data` directory
